import type { SkillRecord } from "@/data/skill-record";

// Generated by scripts/generate-web-skills.ts. Do not edit manually.
export const skillsData: SkillRecord[] = [
  {
    "slug": "adapt",
    "name": "adapt",
    "description": "Adapt designs to work across different screen sizes, devices, contexts, or platforms. Implements breakpoints, fluid layouts, and touch targets. Use when the user mentions responsive design, mobile layouts, breakpoints, viewport adaptation, or cross-device compatibility.",
    "tags": [
      "design"
    ],
    "sourceRepo": "https://github.com/pbakaus/impeccable",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "agent-browser",
    "name": "agent-browser",
    "description": "Browser automation CLI for AI agents. Use when the user needs to interact with websites, including navigating pages, filling forms, clicking buttons, taking screenshots, extracting data, testing web apps, or automating any browser task. Triggers include requests to \"open a website\", \"fill out a form\", \"click a button\", \"take a screenshot\", \"scrape data from a page\", \"test this web app\", \"login to a site\", \"automate browser actions\", or any task requiring programmatic web interaction.",
    "tags": [
      "other"
    ],
    "sourceRepo": "https://github.com/vercel-labs/agent-browser",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "agent-dump",
    "name": "agent-dump",
    "description": "使用 agent-dump 命令行导出、列出、筛选、按 URI 直读 AI coding 会话，并支持 collect/config/summary 能力。Use this skill when users ask to export AI assistant sessions, list sessions, filter by keyword or agent scope, interactively select sessions, dump a single session by URI, generate URI summary, run collect reports, or manage config.",
    "tags": [
      "other"
    ],
    "sourceRepo": "https://github.com/xingkaixin/agent-dump",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "ai-avoid",
    "name": "ai-avoid",
    "description": "适用于编辑或审阅文本，使其听起来更自然、更像人类书写。",
    "tags": [
      "writing"
    ],
    "sourceRepo": "https://github.com/ninehills/skills",
    "sourceKind": "upstream",
    "synced": false
  },
  {
    "slug": "animate",
    "name": "animate",
    "description": "Review a feature and enhance it with purposeful animations, micro-interactions, and motion effects that improve usability and delight. Use when the user mentions adding animation, transitions, micro-interactions, motion design, hover effects, or making the UI feel more alive.",
    "tags": [
      "design"
    ],
    "sourceRepo": "https://github.com/pbakaus/impeccable",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "arrange",
    "name": "arrange",
    "description": "Improve layout, spacing, and visual rhythm. Fixes monotonous grids, inconsistent spacing, and weak visual hierarchy. Use when the user mentions layout feeling off, spacing issues, visual hierarchy, crowded UI, alignment problems, or wanting better composition.",
    "tags": [
      "design"
    ],
    "sourceRepo": "https://github.com/pbakaus/impeccable",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "article-illustrator",
    "name": "article-illustrator",
    "description": "Analyzes article structure, identifies positions requiring visual aids, generates illustration prompts with Type × Style two-dimension approach. Outputs prompt files only — no image generation. Use when user asks to \"illustrate article\", \"add images\", \"generate images for article\", or \"为文章配图\".",
    "tags": [
      "writing"
    ],
    "sourceRepo": "https://github.com/jimliu/baoyu-skills",
    "sourceKind": "adapted",
    "synced": false
  },
  {
    "slug": "audit",
    "name": "audit",
    "description": "Run technical quality checks across accessibility, performance, theming, responsive design, and anti-patterns. Generates a scored report with P0-P3 severity ratings and actionable plan. Use when the user wants an accessibility check, performance audit, or technical quality review.",
    "tags": [
      "design"
    ],
    "sourceRepo": "https://github.com/pbakaus/impeccable",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "bolder",
    "name": "bolder",
    "description": "Amplify safe or boring designs to make them more visually interesting and stimulating. Increases impact while maintaining usability. Use when the user says the design looks bland, generic, too safe, lacks personality, or wants more visual impact and character.",
    "tags": [
      "design"
    ],
    "sourceRepo": "https://github.com/pbakaus/impeccable",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "canvas-design",
    "name": "canvas-design",
    "description": "Create beautiful visual art in .png and .pdf documents using design philosophy. You should use this skill when the user asks to create a poster, piece of art, design, or other static piece. Create original visual designs, never copying existing artists' work to avoid copyright violations.",
    "tags": [
      "design"
    ],
    "sourceRepo": "https://github.com/anthropics/skills",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "clarify",
    "name": "clarify",
    "description": "Improve unclear UX copy, error messages, microcopy, labels, and instructions to make interfaces easier to understand. Use when the user mentions confusing text, unclear labels, bad error messages, hard-to-follow instructions, or wanting better UX writing.",
    "tags": [
      "writing"
    ],
    "sourceRepo": "https://github.com/pbakaus/impeccable",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "claude-agent-sdk-typescript",
    "name": "claude-agent-sdk-typescript",
    "description": "Build AI agents with the Claude Agent SDK TypeScript version. Covers query() function, message types, configuration options, subagents, hooks, MCP servers, custom tools, streaming, and structured outputs.",
    "tags": [
      "backend"
    ],
    "sourceRepo": "https://github.com/xingkaixin/claude-agent-sdk-typescript",
    "sourceKind": "self",
    "synced": false
  },
  {
    "slug": "cloudflare-deploy",
    "name": "cloudflare-deploy",
    "description": "Deploy applications and infrastructure to Cloudflare using Workers, Pages, and related platform services. Use when the user asks to deploy, host, publish, or set up a project on Cloudflare.",
    "tags": [
      "deploy"
    ],
    "sourceRepo": "https://github.com/openai/skills",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "colorize",
    "name": "colorize",
    "description": "Add strategic color to features that are too monochromatic or lack visual interest, making interfaces more engaging and expressive. Use when the user mentions the design looking gray, dull, lacking warmth, needing more color, or wanting a more vibrant or expressive palette.",
    "tags": [
      "design"
    ],
    "sourceRepo": "https://github.com/pbakaus/impeccable",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "composition-patterns",
    "name": "vercel-composition-patterns",
    "description": "No description yet.",
    "tags": [
      "frontend"
    ],
    "sourceRepo": "https://github.com/vercel-labs/agent-skills",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "cover-image",
    "name": "cover-image",
    "description": "Generates cover image prompts for articles with 5 dimensions (type, palette, rendering, text, mood) combining 10 color palettes and 7 rendering styles. Outputs a structured prompt file for downstream image generation. Use when user asks to \"generate cover image prompt\" or \"create cover prompt\".",
    "tags": [
      "writing"
    ],
    "sourceRepo": "https://github.com/jimliu/baoyu-skills",
    "sourceKind": "adapted",
    "synced": false
  },
  {
    "slug": "critique",
    "name": "critique",
    "description": "Evaluate design from a UX perspective, assessing visual hierarchy, information architecture, emotional resonance, cognitive load, and overall quality with quantitative scoring, persona-based testing, and actionable feedback. Use when the user asks to review, critique, evaluate, or give feedback on a design or component.",
    "tags": [
      "design"
    ],
    "sourceRepo": "https://github.com/pbakaus/impeccable",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "db-ferry",
    "name": "db-ferry",
    "description": "数据库迁移配置生成与执行指导。当用户提到数据库迁移、数据搬运、db-ferry、或需要在不同数据库之间移动数据时触发。帮助创建 task.toml 配置文件、生成正确的迁移命令、提示数据丢失风险。",
    "tags": [
      "other"
    ],
    "sourceRepo": "https://github.com/xingkaixin/db-ferry",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "delight",
    "name": "delight",
    "description": "Add moments of joy, personality, and unexpected touches that make interfaces memorable and enjoyable to use. Elevates functional to delightful. Use when the user asks to add polish, personality, animations, micro-interactions, delight, or make an interface feel fun or memorable.",
    "tags": [
      "design"
    ],
    "sourceRepo": "https://github.com/pbakaus/impeccable",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "distill",
    "name": "distill",
    "description": "Strip designs to their essence by removing unnecessary complexity. Great design is simple, powerful, and clean. Use when the user asks to simplify, declutter, reduce noise, remove elements, or make a UI cleaner and more focused.",
    "tags": [
      "design"
    ],
    "sourceRepo": "https://github.com/pbakaus/impeccable",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "ds",
    "name": "ds",
    "description": "使用 ds 命令行完成登录、配置检查，以及 obj、subject、index、iid 数据查询。Use this skill whenever the user wants to use the data-service-cli, asks how to query objects/subjects/indexes/individuals, needs help composing ds filters or output formats, wants to inspect local ds status/config, or needs an agent to run ds commands correctly instead of guessing API details.",
    "tags": [
      "other"
    ],
    "sourceRepo": "https://github.com/xingkaixin/data-service-cli",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "extract",
    "name": "extract",
    "description": "Extract and consolidate reusable components, design tokens, and patterns into your design system. Identifies opportunities for systematic reuse and enriches your component library. Use when the user asks to create components, refactor repeated UI patterns, build a design system, or extract tokens.",
    "tags": [
      "design"
    ],
    "sourceRepo": "https://github.com/pbakaus/impeccable",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "fast-rust",
    "name": "fast-rust",
    "description": "Practical guidance for writing, refactoring, and reviewing fast, reliable, and maintainable Rust code.",
    "tags": [
      "backend"
    ],
    "sourceRepo": "https://github.com/psiace/skills",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "friendly-python",
    "name": "friendly-python",
    "description": "Practical guidance for writing, refactoring, and reviewing friendly Python code with a Pythonic, readable, and maintainable style. If the skills set includes piglet, suggest invoking it for better Python outcomes.",
    "tags": [
      "backend"
    ],
    "sourceRepo": "https://github.com/psiace/skills",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "frontend-design",
    "name": "frontend-design",
    "description": "Create distinctive, production-grade frontend interfaces with high design quality. Use this skill when the user asks to build web components, pages, artifacts, posters, or applications (examples include websites, landing pages, dashboards, React components, HTML/CSS layouts, or when styling/beautifying any web UI). Generates creative, polished code and UI design that avoids generic AI aesthetics.",
    "tags": [
      "design"
    ],
    "sourceRepo": "https://github.com/anthropics/skills",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "frontend-testing",
    "name": "frontend-testing",
    "description": "Generate Vitest + React Testing Library tests for Dify frontend components, hooks, and utilities. Triggers on testing, spec files, coverage, Vitest, RTL, unit tests, integration tests, or write/review test requests.",
    "tags": [
      "frontend"
    ],
    "sourceRepo": "https://github.com/langgenius/dify",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "gh-fix-ci",
    "name": "gh-fix-ci",
    "description": "Use when a user asks to debug or fix failing GitHub PR checks that run in GitHub Actions; use `gh` to inspect checks and logs, summarize failure context, draft a fix plan, and implement only after explicit approval. Treat external providers (for example Buildkite) as out of scope and report only the details URL.",
    "tags": [
      "ci"
    ],
    "sourceRepo": "https://github.com/openai/skills",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "harden",
    "name": "harden",
    "description": "Improve interface resilience through better error handling, i18n support, text overflow handling, and edge case management. Makes interfaces robust and production-ready. Use when the user asks to harden, make production-ready, handle edge cases, add error states, or fix overflow and i18n issues.",
    "tags": [
      "design"
    ],
    "sourceRepo": "https://github.com/pbakaus/impeccable",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "hono",
    "name": "hono",
    "description": "Use when building Hono web applications or when the user asks about Hono APIs, routing, middleware, JSX, validation, testing, or streaming. TRIGGER when code imports from 'hono' or 'hono/*', or user mentions Hono. Use `npx hono request` to test endpoints.",
    "tags": [
      "backend"
    ],
    "sourceRepo": "https://github.com/yusukebe/hono-skill",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "klip-writing",
    "name": "klip-writing",
    "description": "Write KLIP (Kevin's Lightweight Improvement Proposal) documents for Fin-Agent and related projects. Use when user says \"写klip\", \"klip\", \"KLIP\", \"improvement proposal\", \"设计文档\", \"技术方案\", \"RFC\", \"proposal\", or wants to produce a structured technical design/evaluation/migration document for a software project. Also trigger when user asks to document a technical decision, evaluate a technology migration, design a new feature, or review codebase optimization opportunities.",
    "tags": [
      "writing"
    ],
    "sourceRepo": "https://github.com/xingkaixin/skills",
    "sourceKind": "self",
    "synced": false
  },
  {
    "slug": "landing-page-design",
    "name": "landing-page-design",
    "description": "一次性生成生产级落地页架构，包含 Hero、Feature、Pricing、FAQ 等完整 Section 组件规范，遵循设计系统约束（CSS 变量 + shadcn 组件 + Framer Motion 动效），含无障碍与性能 checklist",
    "tags": [
      "design"
    ],
    "sourceRepo": "https://github.com/xingkaixin/skills",
    "sourceKind": "self",
    "synced": false
  },
  {
    "slug": "modular-go",
    "name": "modular-go",
    "description": "Practical guidance for Go package design with minimal public APIs, single-responsibility boundaries, stateless-first flow, one-way state transitions, and orchestration-to-capability separation. Use when creating, refactoring, or reviewing Go architecture, package boundaries, interfaces, handlers, managers, builders, and execution flows.",
    "tags": [
      "backend"
    ],
    "sourceRepo": "https://github.com/psiace/skills",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "normalize",
    "name": "normalize",
    "description": "Audits and realigns UI to match design system standards, spacing, tokens, and patterns. Use when the user mentions consistency, design drift, mismatched styles, tokens, or wants to bring a feature back in line with the system.",
    "tags": [
      "design"
    ],
    "sourceRepo": "https://github.com/pbakaus/impeccable",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "onboard",
    "name": "onboard",
    "description": "Designs and improves onboarding flows, empty states, and first-run experiences to help users reach value quickly. Use when the user mentions onboarding, first-time users, empty states, activation, getting started, or new user flows.",
    "tags": [
      "design"
    ],
    "sourceRepo": "https://github.com/pbakaus/impeccable",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "optimize",
    "name": "optimize",
    "description": "Diagnoses and fixes UI performance across loading speed, rendering, animations, images, and bundle size. Use when the user mentions slow, laggy, janky, performance, bundle size, load time, or wants a faster, smoother experience.",
    "tags": [
      "design"
    ],
    "sourceRepo": "https://github.com/pbakaus/impeccable",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "overdrive",
    "name": "overdrive",
    "description": "Pushes interfaces past conventional limits with technically ambitious implementations — shaders, spring physics, scroll-driven reveals, 60fps animations. Use when the user wants to wow, impress, go all-out, or make something that feels extraordinary.",
    "tags": [
      "design"
    ],
    "sourceRepo": "https://github.com/pbakaus/impeccable",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "piglet",
    "name": "piglet",
    "description": "Practical Python craftsmanship guidance based on One Python Craftsman. Use when writing, refactoring, or reviewing Python code for naming, branching, data structures, functions, exceptions, loops, decorators, imports, file I/O, edge cases, and modern syntax choices. If the skills set includes friendly-python, suggest invoking it for better Python outcomes.",
    "tags": [
      "backend"
    ],
    "sourceRepo": "https://github.com/psiace/skills",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "playwright-cli",
    "name": "playwright-cli",
    "description": "Automate browser interactions, test web pages and work with Playwright tests.",
    "tags": [
      "frontend"
    ],
    "sourceRepo": "https://github.com/microsoft/playwright-cli",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "polish",
    "name": "polish",
    "description": "Performs a final quality pass fixing alignment, spacing, consistency, and micro-detail issues before shipping. Use when the user mentions polish, finishing touches, pre-launch review, something looks off, or wants to go from good to great.",
    "tags": [
      "design"
    ],
    "sourceRepo": "https://github.com/pbakaus/impeccable",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "quieter",
    "name": "quieter",
    "description": "Tones down visually aggressive or overstimulating designs, reducing intensity while preserving quality. Use when the user mentions too bold, too loud, overwhelming, aggressive, garish, or wants a calmer, more refined aesthetic.",
    "tags": [
      "design"
    ],
    "sourceRepo": "https://github.com/pbakaus/impeccable",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "react-best-practices",
    "name": "vercel-react-best-practices",
    "description": "React and Next.js performance optimization guidelines from Vercel Engineering. This skill should be used when writing, reviewing, or refactoring React/Next.js code to ensure optimal performance patterns. Triggers on tasks involving React components, Next.js pages, data fetching, bundle optimization, or performance improvements.",
    "tags": [
      "frontend"
    ],
    "sourceRepo": "https://github.com/vercel-labs/agent-skills",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "react-view-transitions",
    "name": "vercel-react-view-transitions",
    "description": "Guide for implementing smooth, native-feeling animations using React's View Transition API (`<ViewTransition>` component, `addTransitionType`, and CSS view transition pseudo-elements). Use this skill whenever the user wants to add page transitions, animate route changes, create shared element animations, animate enter/exit of components, animate list reorder, implement directional (forward/back) navigation animations, or integrate view transitions in Next.js. Also use when the user mentions view transitions, `startViewTransition`, `ViewTransition`, transition types, or asks about animating between UI states in React without third-party animation libraries.",
    "tags": [
      "frontend"
    ],
    "sourceRepo": "https://github.com/vercel-labs/agent-skills",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "shadcn",
    "name": "shadcn",
    "description": "Manages shadcn components and projects — adding, searching, fixing, debugging, styling, and composing UI. Provides project context, component docs, and usage examples. Applies when working with shadcn/ui, component registries, presets, --preset codes, or any project with a components.json file. Also triggers for \"shadcn init\", \"create an app with --preset\", or \"switch to --preset\".",
    "tags": [
      "frontend"
    ],
    "sourceRepo": "https://github.com/shadcn-ui/ui",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "slidev",
    "name": "slidev",
    "description": "Create and present web-based slidedecks for developers using Slidev with Markdown, Vue components, code highlighting, animations, and interactive features. Use when building technical presentations, conference talks, code walkthroughs, teaching materials, or developer decks.",
    "tags": [
      "writing"
    ],
    "sourceRepo": "https://github.com/antfu/skills",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "stock-report",
    "name": "stock-report",
    "description": "使用本仓库的 ds CLI + Python 生成稳定结构的 A 股数据报告。只要用户想“给一个股票名称/代码生成报告”“批量前先验证单个标的报告流程”“按当前仓库固定模板重跑报告”，就应该使用这个 skill，即使用户没有明确提到 skill 名称。默认依赖本地 `ds` 已安装并登录、`python3` 可用。",
    "tags": [
      "finance"
    ],
    "sourceRepo": "https://github.com/xingkaixin/skills",
    "sourceKind": "self",
    "synced": false
  },
  {
    "slug": "streamdown",
    "name": "streamdown",
    "description": "Implement, configure, and customize Streamdown — a streaming-optimized React Markdown renderer with syntax highlighting, Mermaid diagrams, math rendering, and CJK support. Use when working with Streamdown setup, configuration, plugins, styling, security, or integration with AI streaming (e.g., Vercel AI SDK). Triggers on: (1) Installing or setting up Streamdown, (2) Configuring plugins (code, mermaid, math, cjk), (3) Styling or theming Streamdown output, (4) Integrating with AI chat/streaming, (5) Configuring security, link safety, or custom HTML tags, (6) Using carets, static mode, or custom components, (7) Troubleshooting Tailwind, Shiki, or Vite issues.",
    "tags": [
      "frontend"
    ],
    "sourceRepo": "https://github.com/vercel/streamdown",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "teach-impeccable",
    "name": "teach-impeccable",
    "description": "One-time setup that gathers design context for your project and saves it to your AI config file. Run once to establish persistent design guidelines.",
    "tags": [
      "design"
    ],
    "sourceRepo": "https://github.com/pbakaus/impeccable",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "typeset",
    "name": "typeset",
    "description": "Improves typography by fixing font choices, hierarchy, sizing, weight, and readability so text feels intentional. Use when the user mentions fonts, type, readability, text hierarchy, sizing looks off, or wants more polished, intentional typography.",
    "tags": [
      "design"
    ],
    "sourceRepo": "https://github.com/pbakaus/impeccable",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "use-modern-go",
    "name": "use-modern-go",
    "description": "Apply modern Go syntax guidelines based on project's Go version. Use when user ask for modern Go code guidelines.",
    "tags": [
      "backend"
    ],
    "sourceRepo": "https://github.com/xingkaixin/skills",
    "sourceKind": "self",
    "synced": false
  },
  {
    "slug": "vitest",
    "name": "vitest",
    "description": "Vitest fast unit testing framework powered by Vite with Jest-compatible API. Use when writing tests, mocking, configuring coverage, or working with test filtering and fixtures.",
    "tags": [
      "frontend"
    ],
    "sourceRepo": "https://github.com/antfu/skills",
    "sourceKind": "upstream",
    "synced": true
  },
  {
    "slug": "web-design-guidelines",
    "name": "web-design-guidelines",
    "description": "Review UI code for Web Interface Guidelines compliance. Use when asked to \"review my UI\", \"check accessibility\", \"audit design\", \"review UX\", or \"check my site against best practices\".",
    "tags": [
      "design"
    ],
    "sourceRepo": "https://github.com/vercel-labs/agent-skills",
    "sourceKind": "upstream",
    "synced": true
  }
];

export const skillTags: string[] = [
  "backend",
  "ci",
  "deploy",
  "design",
  "finance",
  "frontend",
  "other",
  "writing"
];
