import type { SkillRecord } from "@/data/skill-record";

// Generated by scripts/generate-web-skills.ts. Do not edit manually.
export const skillsData: SkillRecord[] = [
  {
    "slug": "agent-friendly-cli-design",
    "name": "agent-friendly-cli-design",
    "description": "Use when designing, reviewing, or refactoring a command-line interface that AI agents will invoke — covers non-interactive execution, resource/command layering, unified verbs, output trimming for token budgets, idempotency, and self-correcting error messages. Trigger this when building a new CLI, wrapping an API as a CLI, or auditing an existing CLI for agent usability.",
    "category": "backend",
    "sourceRepo": "https://github.com/xingkaixin/skills",
    "sourceKind": "self",
    "firstAdded": "2026-07-18",
    "lastModified": "2026-07-18"
  },
  {
    "slug": "ai-avoid",
    "name": "ai-avoid",
    "description": "适用于编辑或审阅文本，使其听起来更自然、更像人类书写。",
    "category": "writing",
    "sourceRepo": "https://github.com/ninehills/skills",
    "sourceKind": "upstream",
    "firstAdded": "2026-03-12",
    "lastModified": "2026-03-12"
  },
  {
    "slug": "article-illustrator",
    "name": "article-illustrator",
    "description": "Analyzes article structure, identifies positions requiring visual aids, generates illustration prompts with Type × Style two-dimension approach. Outputs prompt files only — no image generation. Use when user asks to \"illustrate article\", \"add images\", \"generate images for article\", or \"为文章配图\".",
    "category": "writing",
    "sourceRepo": "https://github.com/jimliu/baoyu-skills",
    "sourceKind": "adapted",
    "firstAdded": "2026-03-28",
    "lastModified": "2026-03-28"
  },
  {
    "slug": "bilingual-release-changelog",
    "name": "bilingual-release-changelog",
    "description": "Use when generating a changelog, bumping a version, or publishing a release for a project that maintains Chinese + English changelogs (CHANGELOG.md / CHANGELOG_zh.md / docs/zh + docs/en). Covers commit-range analysis, user-facing wording rules, single-source versioning per language stack (Python hatchling, Go ldflags, npm multi-platform, frontend package.json), tag/CI publishing, and recovery from partially failed releases.",
    "category": "ci",
    "sourceRepo": "https://github.com/xingkaixin/skills",
    "sourceKind": "self",
    "firstAdded": "2026-07-18",
    "lastModified": "2026-07-18"
  },
  {
    "slug": "cloudflare-deploy-migration",
    "name": "cloudflare-deploy-migration",
    "description": "Use when deploying a site to Cloudflare or migrating one off Vercel — static sites to Pages, Next.js via vinext to Workers, full-stack apps to Workers with D1/KV/Durable Objects. Covers wrangler config split (dev/deploy/e2e), secret management, CI with artifact handoff and HOME-isolated wrangler E2E, analytics replacement, and a root-cause pitfall table (charset mojibake, assets-only worker 404, D1 migration naming, bundle guards).",
    "category": "deploy",
    "sourceRepo": "https://github.com/xingkaixin/skills",
    "sourceKind": "self",
    "firstAdded": "2026-07-18",
    "lastModified": "2026-07-18"
  },
  {
    "slug": "code-review-checklist",
    "name": "code-review-checklist",
    "description": "Use when reviewing a pull request, diff, or code change, or when giving feedback on someone else's code. Provides a layered review pass (design → call-sites → naming → run-it → verify) plus rules for what to skip, how to phrase feedback with Socratic questions, and when to say no.",
    "category": "workflow",
    "sourceRepo": "https://github.com/xingkaixin/skills",
    "sourceKind": "self",
    "firstAdded": "2026-07-18",
    "lastModified": "2026-07-18"
  },
  {
    "slug": "codebase-review-loop",
    "name": "codebase-review-loop",
    "description": "Use when auditing a codebase and tracking improvement findings over time — writing numbered improvement-proposal documents with prioritized, evidence-backed findings, verifying findings read-only against current code before fixing (\"ground truth first\"), fixing one finding at a time with a verification gate, writing status back into the document, and raising test coverage with parallel per-module subagents.",
    "category": "workflow",
    "sourceRepo": "https://github.com/xingkaixin/skills",
    "sourceKind": "self",
    "firstAdded": "2026-07-18",
    "lastModified": "2026-07-18"
  },
  {
    "slug": "coding-agent-session-formats",
    "name": "coding-agent-session-formats",
    "description": "Use when parsing, exporting, visualizing, or computing token/cost stats from local coding-agent session files (Codex rollout jsonl, Claude Code project jsonl, Kimi context/wire jsonl, OpenCode/zcode SQLite, Pi tree jsonl). Covers storage paths per agent, message schemas, assistant message ordering/dedup rules, a unified export schema, cache-aware cost calculation, and streaming-parse performance rules for 100-400MB files.",
    "category": "backend",
    "sourceRepo": "https://github.com/xingkaixin/skills",
    "sourceKind": "self",
    "firstAdded": "2026-07-18",
    "lastModified": "2026-07-18"
  },
  {
    "slug": "cover-image",
    "name": "cover-image",
    "description": "Generates cover image prompts for articles with 5 dimensions (type, palette, rendering, text, mood) combining 10 color palettes and 7 rendering styles. Outputs a structured prompt file for downstream image generation. Use when user asks to \"generate cover image prompt\" or \"create cover prompt\".",
    "category": "writing",
    "sourceRepo": "https://github.com/jimliu/baoyu-skills",
    "sourceKind": "adapted",
    "firstAdded": "2026-03-28",
    "lastModified": "2026-03-28"
  },
  {
    "slug": "decision-complete-plan",
    "name": "decision-complete-plan",
    "description": "Use when writing an implementation plan that another session or agent will execute verbatim, or when executing such a plan. Enforces \"decision complete\" handoff: explore code before asking questions, split unknowns into discoverable facts vs user preferences, an eight-section plan template (conclusion-first summary, root cause with file:line evidence, confirmed decisions, minimal-change steps, interface changes, tests, explicit assumptions), and an execute-side verify-before-edit protocol.",
    "category": "workflow",
    "sourceRepo": "https://github.com/xingkaixin/skills",
    "sourceKind": "self",
    "firstAdded": "2026-07-18",
    "lastModified": "2026-07-18"
  },
  {
    "slug": "design-system-as-input-ui",
    "name": "design-system-as-input-ui",
    "description": "Use when generating multi-screen UI with an AI coding agent (Claude Code, Cursor) and the screens come out visually inconsistent — different blues, radii, spacing per screen. Provides a workflow that turns a design system into a reusable *input contract* so every screen references one source of truth instead of guessing pixel-by-pixel. Trigger when building more than one screen, a dashboard, or any product where visual coherence across screens matters.",
    "category": "design",
    "sourceRepo": "https://github.com/xingkaixin/skills",
    "sourceKind": "self",
    "firstAdded": "2026-07-18",
    "lastModified": "2026-07-18"
  },
  {
    "slug": "electron-desktop-release",
    "name": "electron-desktop-release",
    "description": "Use when packaging, signing, notarizing, or securing an Electron desktop app — electron-vite + electron-builder monorepo setup, macOS Developer ID signing and notarization pitfalls (identity naming, timestamp slowness, Team API keys), CI/local build split, and secret storage architecture (safeStorage/Keychain, main-process-only secrets, SQLite is not a secret store).",
    "category": "desktop",
    "sourceRepo": "https://github.com/xingkaixin/skills",
    "sourceKind": "self",
    "firstAdded": "2026-07-18",
    "lastModified": "2026-07-18"
  },
  {
    "slug": "en-zh-literary-translation",
    "name": "en-zh-literary-translation",
    "description": "Use when translating English prose into Chinese and the goal is natural, readable Chinese rather than literal word-for-word output. Applies the 信/达/雅 (faithful/fluent/elegant) framework with concrete transformation rules for sentence restructuring, register, and de-translationese. Do not use for code, terse UI strings, or technical reference tables where literal precision matters more than flow.",
    "category": "writing",
    "sourceRepo": "https://github.com/xingkaixin/skills",
    "sourceKind": "self",
    "firstAdded": "2026-07-18",
    "lastModified": "2026-07-18"
  },
  {
    "slug": "error-message-writing",
    "name": "error-message-writing",
    "description": "Use when writing, reviewing, or suggesting an error message, toast, failure state, or empty/exception copy in any product, UI, or code. Applies the four anti-patterns to avoid and five principles to follow, distinguishes generic vs. unclear failures, and scores each message against a nine-point checklist.",
    "category": "design",
    "sourceRepo": "https://github.com/xingkaixin/skills",
    "sourceKind": "self",
    "firstAdded": "2026-07-18",
    "lastModified": "2026-07-18"
  },
  {
    "slug": "frontend-large-data-performance",
    "name": "frontend-large-data-performance",
    "description": "Use when a frontend must handle large files or streaming data — 50-300MB JSONL parsing, huge document rendering, LLM streaming UIs. Covers benchmark-driven optimization (append-only worker buffers, incremental aggregation, virtual-list/observer conflicts), a first-principles WASM adoption test, streaming UI protocols (init/append chart deltas, stable component references, single in-progress view), and known runtime pitfalls (Bun idleTimeout).",
    "category": "frontend",
    "sourceRepo": "https://github.com/xingkaixin/skills",
    "sourceKind": "self",
    "firstAdded": "2026-07-18",
    "lastModified": "2026-07-18"
  },
  {
    "slug": "git-commit-message",
    "name": "git-commit-message",
    "description": "Use when writing or reviewing a git commit message, drafting commit text before running git commit, or splitting work into commits. Enforces the seven-rule convention (subject/body separation, 50-char imperative subject, 72-char body wrap, explain what/why not how) with concrete good/bad examples.",
    "category": "ci",
    "sourceRepo": "https://github.com/xingkaixin/skills",
    "sourceKind": "self",
    "firstAdded": "2026-07-18",
    "lastModified": "2026-07-18"
  },
  {
    "slug": "ios-on-device-vision-ml",
    "name": "ios-on-device-vision-ml",
    "description": "Use when building on-device visual recognition on iOS — camera viewfinder capture, Vision foreground segmentation (VNGenerateForegroundInstanceMaskRequest), color/classification pipelines, CoreML/LiteRT model evaluation on Mac, and synthetic (AI-generated) datasets for indie developers without real data. Covers WYSIWYG crop geometry, per-instance mask selection, evaluation-set design, distillation-based training routes, and model/privacy boundaries.",
    "category": "ios",
    "sourceRepo": "https://github.com/xingkaixin/skills",
    "sourceKind": "self",
    "firstAdded": "2026-07-18",
    "lastModified": "2026-07-18"
  },
  {
    "slug": "ios-recording-system-integration",
    "name": "ios-recording-system-integration",
    "description": "Use when building iOS recording features that integrate with Live Activities (Dynamic Island), the Action Button (App Intents), background audio, or realtime ASR over WebSocket. Covers the hard iOS boundaries (first mic activation must be foreground, Action Button assignment is unreadable, Live Activity is not a streaming channel), an intent state machine with audioSessionPrimed fallback, Dynamic Island debugging, and two ASR protocol paradigms (OpenAI-Realtime JSON vs binary frame).",
    "category": "ios",
    "sourceRepo": "https://github.com/xingkaixin/skills",
    "sourceKind": "self",
    "firstAdded": "2026-07-18",
    "lastModified": "2026-07-18"
  },
  {
    "slug": "ios-widget-appstore-shipping",
    "name": "ios-widget-appstore-shipping",
    "description": "Use when building WidgetKit extensions or shipping an iOS app to the App Store — App Group data sharing (widgets cannot rely on the main app bundle), timeline/config refresh pitfalls, simulator-vs-device icon debugging, Info.plist encryption exemption (ITSAppUsesNonExemptEncryption in every bundle), TestFlight flow, screenshot rules (no fake status bars), review-rejection root-cause analysis (Kids Category, 2.3.10, 5.1.1 BYOK disclosure), and localization via system settings.",
    "category": "ios",
    "sourceRepo": "https://github.com/xingkaixin/skills",
    "sourceKind": "self",
    "firstAdded": "2026-07-18",
    "lastModified": "2026-07-18"
  },
  {
    "slug": "issue-driven-dev-loop",
    "name": "issue-driven-dev-loop",
    "description": "Use when working through a backlog of issues one by one — picking up an issue, refining its design, implementing, opening a PR, updating issue status after merge, and moving to the next. Covers local file-based .issues/ trackers (meta.yaml, status-as-directory), design-confirm-implement loops, branch/commit conventions, draft PRs with CI follow-up, and parallelizing independent issues with subagents.",
    "category": "workflow",
    "sourceRepo": "https://github.com/xingkaixin/skills",
    "sourceKind": "self",
    "firstAdded": "2026-07-18",
    "lastModified": "2026-07-18"
  },
  {
    "slug": "issue-tracker",
    "name": "issue-tracker",
    "description": "Local Markdown issue tracking system for managing feature requests, bugs, and version iterations within project repositories. Use when the user says \"创建 issue\", \"新建需求\", \"建 bug\", \"issue\", \"需求跟踪\", \"版本迭代\", \"milestone\", \"里程碑\", \"看板\", \"issue 状态\", \"关联 PR\", \"更新进度\", \"归档\", \"backlog\", or wants to create, update, query, move, or visualize issues stored in the local .issues/ directory. Also trigger when the user asks to generate an HTML view of an issue, check PR status, move issues between milestones or status lanes, initialize issue tracking for a project, or produce a summary of current iteration progress. Trigger even if the user just says \"开个 issue\" or references an issue ID like \"RD-400\".",
    "category": "workflow",
    "sourceRepo": "https://github.com/xingkaixin/skills",
    "sourceKind": "self",
    "firstAdded": "2026-07-18",
    "lastModified": "2026-07-18"
  },
  {
    "slug": "klip-writing",
    "name": "klip-writing",
    "description": "Write KLIP (Kevin's Lightweight Improvement Proposal) documents for Fin-Agent and related projects. Use when user says \"写klip\", \"klip\", \"KLIP\",\"improvement proposal\", \"设计文档\", \"技术方案\", \"RFC\", \"proposal\",or wants to produce a structured technical design/evaluation/migration document for a software project. Also trigger when user asks to document a technical decision, evaluate a technology migration, design a new feature, or review codebase optimization opportunities.",
    "category": "writing",
    "sourceRepo": "https://github.com/xingkaixin/skills",
    "sourceKind": "self",
    "firstAdded": "2026-04-02",
    "lastModified": "2026-04-21"
  },
  {
    "slug": "monorepo-architecture-principles",
    "name": "monorepo-architecture-principles",
    "description": "Use when organizing a monorepo, splitting a single repo into packages, evaluating an architecture migration, or reviewing structural decisions. Covers the layered apps/packages paradigm (single contract layer, one-way dependency DAG, bottom-up extraction order), ten recurring architecture principles (single data source with no fallback forks, execution-location correctness, cost-vs-pain gating for rewrites), named anti-patterns, and native-module/packaging pitfalls.",
    "category": "backend",
    "sourceRepo": "https://github.com/xingkaixin/skills",
    "sourceKind": "self",
    "firstAdded": "2026-07-18",
    "lastModified": "2026-07-18"
  },
  {
    "slug": "react-state-management-decisions",
    "name": "react-state-management-decisions",
    "description": "Use when deciding where React state should live or planning a state-management migration — useState vs useRef vs useMemo vs Context vs Zustand vs React Query. Provides a decision tree, a useRef semantic classification (most refs should NOT migrate), Zustand/React Query responsibility boundaries, progressive migration strategy, and persist-based draft state patterns.",
    "category": "frontend",
    "sourceRepo": "https://github.com/xingkaixin/skills",
    "sourceKind": "self",
    "firstAdded": "2026-07-18",
    "lastModified": "2026-07-18"
  },
  {
    "slug": "save-the-cat-writing",
    "name": "save-the-cat-writing",
    "description": "Save the Cat 方法论改编的 AI 辅助开发类公众号写作自检清单。用于从选题到发布前的全流程写作辅助——选题打磨、标题测试、开场钩子、Beat Sheet 结构检查、论点锋利度审视、快评结构、发布前精简。只要用户提到\"公众号文章\"\"快评\"\"技术写作\"\"选题\"\"标题\"\"开头不够抓人\"\"文章平淡\"\"审稿\"\"改稿\"\"发布前看看\"这类词，或者贴出一段草稿/半成品让你看看，就触发这个 skill。凯哥（Kevin）写 AI 开发类内容时用这套方法，对\"正确但无聊\"\"万金油结尾\"\"泛泛而谈\"零容忍。",
    "category": "writing",
    "sourceRepo": "https://github.com/xingkaixin/skills",
    "sourceKind": "self",
    "firstAdded": "2026-04-24",
    "lastModified": "2026-04-24"
  },
  {
    "slug": "stock-report",
    "name": "stock-report",
    "description": "使用本仓库的 ds CLI + Python 生成稳定结构的 A 股数据报告。只要用户想“给一个股票名称/代码生成报告”“批量前先验证单个标的报告流程”“按当前仓库固定模板重跑报告”，就应该使用这个 skill，即使用户没有明确提到 skill 名称。默认依赖本地 `ds` 已安装并登录、`python3` 可用。",
    "category": "finance",
    "sourceRepo": "https://github.com/xingkaixin/skills",
    "sourceKind": "self",
    "firstAdded": "2026-03-11",
    "lastModified": "2026-03-11"
  },
  {
    "slug": "tauri-menubar-agent-app",
    "name": "tauri-menubar-agent-app",
    "description": "Use when building a macOS menu-bar (tray) app with Tauri v2, especially one that observes external CLI agents via hooks — covers native window layering with objc2 (transparent windows, NSStatusWindowLevel, flipped coordinates), Unix-socket IPC from hook bridge binaries, multi-agent event normalization, and non-intrusive interaction design.",
    "category": "desktop",
    "sourceRepo": "https://github.com/xingkaixin/skills",
    "sourceKind": "self",
    "firstAdded": "2026-07-18",
    "lastModified": "2026-07-18"
  },
  {
    "slug": "tech-stack-scaffolding",
    "name": "tech-stack-scaffolding",
    "description": "Use when bootstrapping a new project or aligning an existing one to house conventions — frontend/fullstack (bun+vite+react+tailwind v4+shadcn+oxlint/oxfmt), browser extensions (WXT/MV3), Python CLI (uv+hatchling+Typer+just), Go CLI (mise+golangci-lint+just). Provides drop-in config templates, script naming conventions per stack, icon/zip pipelines, and the concise AGENTS.md format (readable in one minute).",
    "category": "backend",
    "sourceRepo": "https://github.com/xingkaixin/skills",
    "sourceKind": "self",
    "firstAdded": "2026-07-18",
    "lastModified": "2026-07-18"
  },
  {
    "slug": "triple-mind-deep-reading",
    "name": "triple-mind-deep-reading",
    "description": "Use when analyzing a long-form article, podcast transcript, talk, paper, or a complex decision in depth — and a flat summary is not enough. Runs the source through three deliberate lenses (Challenger, Builder, Practitioner) to surface weaknesses, extensions, and actionable takeaways. Do not use for quick factual lookups, short texts, or when the user only wants a plain summary.",
    "category": "writing",
    "sourceRepo": "https://github.com/xingkaixin/skills",
    "sourceKind": "self",
    "firstAdded": "2026-07-18",
    "lastModified": "2026-07-18"
  },
  {
    "slug": "use-modern-go",
    "name": "use-modern-go",
    "description": "Apply modern Go syntax guidelines based on project's Go version. Use when user ask for modern Go code guidelines.",
    "category": "backend",
    "sourceRepo": "https://github.com/xingkaixin/skills",
    "sourceKind": "self",
    "firstAdded": "2026-03-12",
    "lastModified": "2026-03-12"
  },
  {
    "slug": "writing-agent-skills",
    "name": "writing-agent-skills",
    "description": "Use when creating, rewriting, reviewing, or testing an agent skill (a SKILL.md package for Claude Code, Codex, or any agent) — covers picking the skill type, writing directive instructions, engineering the description as a routing contract, splitting deterministic work into scripts, and building an eval harness to verify it. Trigger when someone says \"write a skill\", \"improve this skill\", \"why doesn't my skill trigger\", \"test/eval this skill\", or is designing reusable operational workflows for an agent.",
    "category": "workflow",
    "sourceRepo": "https://github.com/xingkaixin/skills",
    "sourceKind": "self",
    "firstAdded": "2026-07-18",
    "lastModified": "2026-07-18"
  }
];

export const skillCategories: string[] = [
  "backend",
  "ci",
  "deploy",
  "design",
  "desktop",
  "finance",
  "frontend",
  "ios",
  "workflow",
  "writing"
];
