import { execFile } from "node:child_process";
import { promises as fs } from "node:fs";
import path from "node:path";
import { promisify } from "node:util";
import { marked, type Token, type Tokens } from "marked";
import {
  categoryMetadata,
  SITE_REPO,
  skillCatalog,
} from "./config.ts";
import { parseSkillMarkdown, renderSkillBody } from "./markdown.ts";
import type { SkillLocation, SkillRecord } from "./types.ts";

const execFileAsync = promisify(execFile);

interface SkillEntry {
  record: SkillRecord;
  content: string;
}

interface Artifact {
  path: string;
  content: string;
}

interface GitDates {
  firstAdded: string;
  lastModified: string;
}

export async function publishCatalog(
  repoRoot: string,
  checkOnly: boolean,
): Promise<void> {
  const artifacts = await buildArtifacts(repoRoot);
  if (checkOnly) {
    await assertArtifactsCurrent(repoRoot, artifacts);
    return;
  }

  await Promise.all(
    artifacts.map(async (artifact) => {
      const outputPath = path.join(repoRoot, artifact.path);
      await fs.mkdir(path.dirname(outputPath), { recursive: true });
      await fs.writeFile(outputPath, artifact.content, "utf8");
    }),
  );
  console.log(`Generated ${artifacts.length} catalog artifacts.`);
}

export async function buildArtifacts(repoRoot: string): Promise<Artifact[]> {
  const locations = await discoverSkills(repoRoot);
  assertUniqueSlugs(locations);
  assertKnownCategories(locations);
  await validateLocalMarkdownLinks(repoRoot, locations);
  const datesByPath = await readGitDates(repoRoot);
  const entries = await Promise.all(
    locations.map((location) => readSkill(repoRoot, location, datesByPath)),
  );
  entries.sort((left, right) =>
    left.record.slug.localeCompare(right.record.slug),
  );

  return [
    ...buildWebArtifacts(entries),
    buildClaudeMarketplace(entries),
    buildCodexMarketplace(entries),
    ...buildCodexPluginManifests(entries),
  ];
}

async function discoverSkills(repoRoot: string): Promise<SkillLocation[]> {
  const skillsRoot = path.join(repoRoot, "skills");
  const categories = await fs.readdir(skillsRoot, { withFileTypes: true });
  const locations = await Promise.all(
    categories
      .filter((entry) => entry.isDirectory())
      .map(async (category) => {
        const entries = await fs.readdir(path.join(skillsRoot, category.name), {
          withFileTypes: true,
        });
        return entries
          .filter((entry) => entry.isDirectory())
          .map((entry) => ({ category: category.name, slug: entry.name }));
      }),
  );
  return locations.flat();
}

async function readSkill(
  repoRoot: string,
  location: SkillLocation,
  datesByPath: Map<string, GitDates>,
): Promise<SkillEntry> {
  const relativePath = path.posix.join(
    "skills",
    location.category,
    location.slug,
    "SKILL.md",
  );
  const skillPath = path.join(repoRoot, relativePath);
  const markdown = await fs.readFile(skillPath, "utf8");
  const parsed = parseSkillMarkdown(markdown, location.slug);
  const source = skillCatalog[location.slug]?.source ?? {
    kind: "self" as const,
    repo: SITE_REPO,
  };
  const dates = datesByPath.get(relativePath) ?? (await datesFromMtime(skillPath));

  return {
    record: {
      slug: location.slug,
      name: parsed.name,
      description: parsed.description,
      category: location.category,
      sourceRepo: source.repo,
      sourceKind: source.kind,
      firstAdded: dates.firstAdded,
      lastModified: dates.lastModified,
      language: parsed.language,
    },
    content: renderSkillBody(parsed.body, location.category, location.slug),
  };
}

function buildWebArtifacts(entries: SkillEntry[]): Artifact[] {
  const records = entries.map((entry) => entry.record);
  const categories = Array.from(
    new Set(records.map((record) => record.category)),
  ).sort((left, right) => left.localeCompare(right));
  const contentBySlug = Object.fromEntries(
    entries.map((entry) => [entry.record.slug, entry.content]),
  );

  return [
    {
      path: "apps/web/src/data/skills.generated.ts",
      content: [
        'import type { SkillRecord } from "@/data/skill-record";',
        "",
        "// Generated by scripts/generate-web-skills.ts. Do not edit manually.",
        `export const skillsData: SkillRecord[] = ${JSON.stringify(records, null, 2)};`,
        "",
        `export const skillCategories: string[] = ${JSON.stringify(categories, null, 2)};`,
        "",
      ].join("\n"),
    },
    {
      path: "apps/web/src/data/skills.content.generated.ts",
      content: [
        "// Generated by scripts/generate-web-skills.ts. Do not edit manually.",
        `export const skillContent: Record<string, string> = ${JSON.stringify(contentBySlug, null, 2)};`,
        "",
      ].join("\n"),
    },
  ];
}

function buildClaudeMarketplace(entries: SkillEntry[]): Artifact {
  const plugins = groupedEntries(entries).map(([category, categoryEntries]) => ({
    name: `${category}-skills`,
    description: categoryMetadata[category].description,
    source: "./",
    strict: false,
    skills: categoryEntries.map(
      (entry) => `./skills/${category}/${entry.record.slug}`,
    ),
  }));

  return jsonArtifact(".claude-plugin/marketplace.json", {
    name: "xingkaixin-skills",
    owner: {
      name: "XingKaiXin",
      email: "xingkaixin@gmail.com",
    },
    metadata: {
      description: "XingKaiXin skills organized by category",
      version: "1.0.0",
    },
    plugins,
  });
}

function buildCodexMarketplace(entries: SkillEntry[]): Artifact {
  const plugins = groupedEntries(entries).map(([category]) => ({
    name: `${category}-skills`,
    source: {
      source: "local",
      path: `./plugins/${category}-skills`,
    },
    policy: {
      installation: "AVAILABLE",
      authentication: "ON_INSTALL",
    },
    category: categoryMetadata[category].codexCategory,
  }));

  return jsonArtifact(".agents/plugins/marketplace.json", {
    name: "xingkaixin-skills",
    interface: {
      displayName: "XingKaiXin Skills",
    },
    plugins,
  });
}

function buildCodexPluginManifests(entries: SkillEntry[]): Artifact[] {
  return groupedEntries(entries).map(([category]) => {
    const metadata = categoryMetadata[category];
    return jsonArtifact(`plugins/${category}-skills/.codex-plugin/plugin.json`, {
      name: `${category}-skills`,
      version: "1.0.0",
      description: `${metadata.description}.`,
      author: {
        name: "XingKaiXin",
        email: "xingkaixin@gmail.com",
      },
      repository: SITE_REPO,
      skills: "./skills/",
      interface: {
        displayName: metadata.displayName,
        shortDescription: metadata.shortDescription,
        longDescription: metadata.longDescription,
        developerName: "XingKaiXin",
        category: metadata.codexCategory,
        capabilities: ["Read", "Write"],
        defaultPrompt: [metadata.defaultPrompt],
      },
    });
  });
}

function groupedEntries(
  entries: SkillEntry[],
): Array<[string, SkillEntry[]]> {
  const byCategory = new Map<string, SkillEntry[]>();
  for (const entry of entries) {
    const categoryEntries = byCategory.get(entry.record.category) ?? [];
    categoryEntries.push(entry);
    byCategory.set(entry.record.category, categoryEntries);
  }
  return Array.from(byCategory.entries()).sort(([left], [right]) =>
    left.localeCompare(right),
  );
}

function jsonArtifact(artifactPath: string, value: unknown): Artifact {
  return {
    path: artifactPath,
    content: `${JSON.stringify(value, null, 2)}\n`,
  };
}

async function assertArtifactsCurrent(
  repoRoot: string,
  artifacts: Artifact[],
): Promise<void> {
  const stale: string[] = [];
  for (const artifact of artifacts) {
    try {
      const current = await fs.readFile(
        path.join(repoRoot, artifact.path),
        "utf8",
      );
      if (current !== artifact.content) {
        stale.push(artifact.path);
      }
    } catch {
      stale.push(artifact.path);
    }
  }
  if (stale.length > 0) {
    throw new Error(
      `Generated catalog artifacts are stale:\n${stale.map((item) => `- ${item}`).join("\n")}`,
    );
  }
}

function assertUniqueSlugs(locations: SkillLocation[]): void {
  const categoriesBySlug = new Map<string, string>();
  for (const { category, slug } of locations) {
    const existingCategory = categoriesBySlug.get(slug);
    if (existingCategory) {
      throw new Error(
        `Duplicate skill slug "${slug}" in categories "${existingCategory}" and "${category}".`,
      );
    }
    categoriesBySlug.set(slug, category);
  }
}

function assertKnownCategories(locations: SkillLocation[]): void {
  const categories = new Set(locations.map((location) => location.category));
  const unknown = Array.from(categories).filter(
    (category) => !categoryMetadata[category],
  );
  const unused = Object.keys(categoryMetadata).filter(
    (category) => !categories.has(category),
  );
  if (unknown.length > 0 || unused.length > 0) {
    throw new Error(
      [
        unknown.length > 0 ? `Unknown categories: ${unknown.join(", ")}` : "",
        unused.length > 0 ? `Unused categories: ${unused.join(", ")}` : "",
      ]
        .filter(Boolean)
        .join("\n"),
    );
  }
}

async function validateLocalMarkdownLinks(
  repoRoot: string,
  locations: SkillLocation[],
): Promise<void> {
  const failures: string[] = [];
  for (const location of locations) {
    const skillRoot = path.join(repoRoot, "skills", location.category, location.slug);
    const entries = await fs.readdir(skillRoot, {
      recursive: true,
      withFileTypes: true,
    });
    const markdownFiles = entries
      .filter((entry) => entry.isFile() && entry.name.endsWith(".md"))
      .map((entry) => path.join(entry.parentPath, entry.name));
    for (const markdownPath of markdownFiles) {
      const markdown = await fs.readFile(markdownPath, "utf8");
      const links: string[] = [];
      marked.walkTokens(marked.lexer(markdown), (token: Token) => {
        if (token.type === "link" || token.type === "image") {
          links.push((token as Tokens.Link | Tokens.Image).href);
        }
      });
      for (const href of links) {
        if (!isLocalReference(href)) {
          continue;
        }
        const target = href.split(/[?#]/, 1)[0];
        if (!target) {
          continue;
        }
        const resolved = path.resolve(path.dirname(markdownPath), target);
        try {
          await fs.access(resolved);
        } catch {
          failures.push(
            `${path.relative(repoRoot, markdownPath)} -> ${href}`,
          );
        }
      }
    }
  }
  if (failures.length > 0) {
    throw new Error(`Broken local Markdown links:\n${failures.join("\n")}`);
  }
}

function isLocalReference(href: string): boolean {
  return (
    !href.startsWith("#") &&
    !href.startsWith("/") &&
    !href.startsWith("//") &&
    !/^[a-z][a-z0-9+.-]*:/i.test(href)
  );
}

async function readGitDates(repoRoot: string): Promise<Map<string, GitDates>> {
  const { stdout } = await execFileAsync(
    "git",
    [
      "log",
      "--format=__COMMIT__%cs",
      "--name-status",
      "--find-renames",
      "--diff-filter=AMR",
      "--",
      "skills",
    ],
    { cwd: repoRoot, maxBuffer: 16 * 1024 * 1024 },
  );
  const dates = new Map<string, GitDates>();
  const aliases = new Map<string, string>();
  let currentDate = "";

  for (const line of stdout.split("\n")) {
    if (line.startsWith("__COMMIT__")) {
      currentDate = line.slice("__COMMIT__".length);
      continue;
    }
    if (!currentDate || !line) {
      continue;
    }
    const [status, firstPath, secondPath] = line.split("\t");
    if (!firstPath) {
      continue;
    }
    if (status.startsWith("R") && secondPath) {
      const currentPath = aliases.get(secondPath) ?? secondPath;
      aliases.set(firstPath, currentPath);
      continue;
    }
    const currentPath = aliases.get(firstPath) ?? firstPath;
    aliases.set(firstPath, currentPath);
    recordGitDate(dates, currentPath, currentDate);
  }
  return dates;
}

function recordGitDate(
  dates: Map<string, GitDates>,
  filePath: string,
  date: string,
): void {
  const existing = dates.get(filePath);
  dates.set(filePath, {
    lastModified: existing?.lastModified ?? date,
    firstAdded: date,
  });
}

async function datesFromMtime(filePath: string): Promise<GitDates> {
  const stat = await fs.stat(filePath);
  const date = stat.mtime.toISOString().split("T")[0];
  return { firstAdded: date, lastModified: date };
}
