import { promises as fs } from "node:fs";
import path from "node:path";
import { SITE_REPO, skillCatalog } from "../apps/web/src/data/catalog.ts";
import type { SkillRecord } from "../apps/web/src/data/skill-record.ts";

const repoRoot = process.cwd();
const skillsRoot = path.join(repoRoot, "skills");
const outputPath = path.join(repoRoot, "apps", "web", "src", "data", "skills.generated.ts");

type Frontmatter = Record<string, string>;

async function main(): Promise<void> {
  const entries = await fs.readdir(skillsRoot, { withFileTypes: true });
  const skills = await Promise.all(
    entries
      .filter((entry) => entry.isDirectory())
      .map((entry) => readSkill(entry.name)),
  );

  const sortedSkills = skills
    .filter((skill): skill is SkillRecord => skill !== null)
    .sort((left, right) => left.slug.localeCompare(right.slug));
  const tags = Array.from(new Set(sortedSkills.flatMap((skill) => skill.tags))).sort((a, b) =>
    a.localeCompare(b),
  );

  const content = [
    'import type { SkillRecord } from "@/data/skill-record";',
    "",
    "// Generated by scripts/generate-web-skills.ts. Do not edit manually.",
    `export const skillsData: SkillRecord[] = ${JSON.stringify(sortedSkills, null, 2)};`,
    "",
    `export const skillTags: string[] = ${JSON.stringify(tags, null, 2)};`,
    "",
  ].join("\n");

  await fs.writeFile(outputPath, content, "utf8");
  console.log(`Generated ${path.relative(repoRoot, outputPath)} with ${sortedSkills.length} skills.`);
}

async function readSkill(slug: string): Promise<SkillRecord | null> {
  const directory = path.join(skillsRoot, slug);
  const skillMdPath = path.join(directory, "SKILL.md");
  const syncMdPath = path.join(directory, "SYNC.md");
  const [skillMd, syncMd] = await Promise.all([
    readOptionalFile(skillMdPath),
    readOptionalFile(syncMdPath),
  ]);

  if (skillMd === null) {
    return null;
  }

  const frontmatter = parseFrontmatter(skillMd);
  const catalogEntry = skillCatalog[slug];
  const synced = syncMd !== null;
  const sourceRepo = catalogEntry?.source?.repo ?? extractSyncRepo(syncMd) ?? SITE_REPO;
  const sourceKind = catalogEntry?.source?.kind ?? (synced ? "upstream" : "self");

  return {
    slug,
    name: frontmatter.name || slug,
    description: frontmatter.description || "No description yet.",
    tags: catalogEntry?.tags ?? [],
    sourceRepo,
    sourceKind,
    synced,
  };
}

async function readOptionalFile(filePath: string): Promise<string | null> {
  try {
    return await fs.readFile(filePath, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return null;
    }
    throw error;
  }
}

function extractSyncRepo(content: string | null): string | null {
  if (!content) {
    return null;
  }

  const match = content.match(/- Source Repo:\s*`([^`]+)`/);
  return match?.[1] ?? null;
}

function parseFrontmatter(markdown: string): Frontmatter {
  const match = markdown.match(/^---\n([\s\S]*?)\n---/);
  if (!match) {
    return {};
  }

  const lines = match[1].split("\n");
  const result: Frontmatter = {};

  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index];
    const scalar = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!scalar) {
      continue;
    }

    const [, rawKey, rawValue] = scalar;
    if (rawValue === "|" || rawValue === "|-" || rawValue === ">" || rawValue === ">-") {
      const block: string[] = [];
      let innerIndex = index + 1;
      for (; innerIndex < lines.length; innerIndex += 1) {
        const blockLine = lines[innerIndex];
        if (!blockLine.startsWith("  ")) {
          break;
        }
        block.push(blockLine.slice(2));
      }
      result[rawKey] = collapseBlock(rawValue, block);
      index = innerIndex - 1;
      continue;
    }

    result[rawKey] = normalizeScalar(rawValue);
  }

  return result;
}

function normalizeScalar(value: string): string {
  return value.trim().replace(/^['"]|['"]$/g, "");
}

function collapseBlock(indicator: string, lines: string[]): string {
  if (indicator.startsWith(">")) {
    return lines.map((line) => line.trim()).join(" ").trim();
  }

  return lines.join("\n").trim();
}

await main();
