import { execFile } from "node:child_process";
import { promises as fs } from "node:fs";
import path from "node:path";
import { promisify } from "node:util";
import { marked } from "marked";
import { SITE_REPO, skillCatalog } from "../apps/web/src/data/catalog.ts";
import type { SkillRecord } from "../apps/web/src/data/skill-record.ts";

const repoRoot = process.cwd();
const skillsRoot = path.join(repoRoot, "skills");
const dataDir = path.join(repoRoot, "apps", "web", "src", "data");
const outputPath = path.join(dataDir, "skills.generated.ts");
const contentOutputPath = path.join(dataDir, "skills.content.generated.ts");
const execFileAsync = promisify(execFile);

interface SkillEntry {
  record: SkillRecord;
  content: string;
}

type Frontmatter = Record<string, string>;

async function main(): Promise<void> {
  const entries = await fs.readdir(skillsRoot, { withFileTypes: true });
  const skills = await Promise.all(
    entries
      .filter((entry) => entry.isDirectory())
      .map((entry) => readSkill(entry.name)),
  );

  const sortedEntries = skills
    .filter((entry): entry is SkillEntry => entry !== null)
    .sort((left, right) => left.record.slug.localeCompare(right.record.slug));
  const sortedSkills = sortedEntries.map((entry) => entry.record);
  const tags = Array.from(new Set(sortedSkills.flatMap((skill) => skill.tags))).sort((a, b) =>
    a.localeCompare(b),
  );

  const content = [
    'import type { SkillRecord } from "@/data/skill-record";',
    "",
    "// Generated by scripts/generate-web-skills.ts. Do not edit manually.",
    `export const skillsData: SkillRecord[] = ${JSON.stringify(sortedSkills, null, 2)};`,
    "",
    `export const skillTags: string[] = ${JSON.stringify(tags, null, 2)};`,
    "",
  ].join("\n");

  const contentMap = Object.fromEntries(
    sortedEntries.map((entry) => [entry.record.slug, entry.content]),
  );
  const contentFile = [
    "// Generated by scripts/generate-web-skills.ts. Do not edit manually.",
    `export const skillContent: Record<string, string> = ${JSON.stringify(contentMap, null, 2)};`,
    "",
  ].join("\n");

  await fs.writeFile(outputPath, content, "utf8");
  await fs.writeFile(contentOutputPath, contentFile, "utf8");
  console.log(`Generated ${path.relative(repoRoot, outputPath)} with ${sortedSkills.length} skills.`);
}

async function readSkill(slug: string): Promise<SkillEntry | null> {
  const directory = path.join(skillsRoot, slug);
  const skillMdPath = path.join(directory, "SKILL.md");
  const syncMdPath = path.join(directory, "SYNC.md");
  const [skillMd, syncMd] = await Promise.all([
    readOptionalFile(skillMdPath),
    readOptionalFile(syncMdPath),
  ]);

  if (skillMd === null) {
    return null;
  }

  const frontmatter = parseFrontmatter(skillMd);
  const catalogEntry = skillCatalog[slug];
  const synced = syncMd !== null;
  const sourceRepo = catalogEntry?.source?.repo ?? extractSyncRepo(syncMd) ?? SITE_REPO;
  const sourceKind = catalogEntry?.source?.kind ?? (synced ? "upstream" : "self");
  const [firstAdded, lastModified] = await Promise.all([
    readGitDate(skillMdPath, "first"),
    readGitDate(skillMdPath, "last"),
  ]);

  return {
    record: {
      slug,
      name: frontmatter.name || slug,
      description: frontmatter.description || "No description yet.",
      tags: catalogEntry?.tags ?? [],
      sourceRepo,
      sourceKind,
      synced,
      firstAdded,
      lastModified,
    },
    content: renderSkillBody(skillMd),
  };
}

function renderSkillBody(markdown: string): string {
  const body = markdown.replace(/^---\n[\s\S]*?\n---\n?/, "").trim();
  const html = marked.parse(body, { async: false, gfm: true });
  return demoteHeadings(sanitizeHtml(html));
}

// The page already renders an <h1>; keep body headings below it so each page has one h1.
function demoteHeadings(html: string): string {
  let result = html;
  for (const level of [5, 4, 3, 2, 1]) {
    result = result.replace(new RegExp(`<(/?)h${level}([ >])`, "gi"), `<$1h${level + 1}$2`);
  }
  return result;
}

// SKILL.md bodies include vendored third-party docs, so drop active/embedded content.
function sanitizeHtml(html: string): string {
  return html
    .replace(/<(script|style|iframe|object|embed)[\s\S]*?<\/\1>/gi, "")
    .replace(/\son\w+="[^"]*"/gi, "")
    .replace(/javascript:/gi, "");
}

async function readGitDate(filePath: string, boundary: "first" | "last"): Promise<string> {
  const relativePath = path.relative(repoRoot, filePath);
  const args =
    boundary === "last"
      ? ["log", "-1", "--format=%cs", "--", relativePath]
      : ["log", "--diff-filter=A", "--format=%cs", "--", relativePath];
  const { stdout } = await execFileAsync("git", args, { cwd: repoRoot });
  const dates = stdout.trim().split("\n").filter(Boolean);
  const committedDate = boundary === "last" ? dates.at(0) : dates.at(-1);
  if (committedDate) {
    return committedDate;
  }

  const stat = await fs.stat(filePath);
  return stat.mtime.toISOString().split("T")[0];
}

async function readOptionalFile(filePath: string): Promise<string | null> {
  try {
    return await fs.readFile(filePath, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return null;
    }
    throw error;
  }
}

function extractSyncRepo(content: string | null): string | null {
  if (!content) {
    return null;
  }

  const match = content.match(/- Source Repo:\s*`([^`]+)`/);
  return match?.[1] ?? null;
}

function parseFrontmatter(markdown: string): Frontmatter {
  const match = markdown.match(/^---\n([\s\S]*?)\n---/);
  if (!match) {
    return {};
  }

  const lines = match[1].split("\n");
  const result: Frontmatter = {};

  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index];
    const scalar = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!scalar) {
      continue;
    }

    const [, rawKey, rawValue] = scalar;
    if (rawValue === "|" || rawValue === "|-" || rawValue === ">" || rawValue === ">-") {
      const block: string[] = [];
      let innerIndex = index + 1;
      for (; innerIndex < lines.length; innerIndex += 1) {
        const blockLine = lines[innerIndex];
        if (!blockLine.startsWith("  ")) {
          break;
        }
        block.push(blockLine.slice(2));
      }
      result[rawKey] = collapseBlock(rawValue, block);
      index = innerIndex - 1;
      continue;
    }

    result[rawKey] = normalizeScalar(rawValue);
  }

  return result;
}

function normalizeScalar(value: string): string {
  return value.trim().replace(/^['"]|['"]$/g, "");
}

function collapseBlock(indicator: string, lines: string[]): string {
  if (indicator.startsWith(">")) {
    return lines.map((line) => line.trim()).join(" ").trim();
  }

  return lines.join("\n").trim();
}

await main();
